image: crowdar/pipeline:2.0.1

stages:
  - Deploy

deploy Nexus:
  stage: Deploy
  script:
    - sh create-settings.sh
    - mvn -B -s settings.xml verify
    - mvn -B -s settings.xml deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "release"'
    - if: '$CI_COMMIT_BRANCH == "main"'

Deploy OSSRH:
  stage: Deploy
  script:
    - sh create-settings.sh # Create our settings.xml file.  Will fail if environment variables aren't set properly.
    - openssl aes-256-cbc -pass pass:$OPENSSL_PWD -in private-key.gpg.enc -out private-key.gpg -d -md sha256
    - gpg --batch --import ${GPG_KEY_FILE}
    - mvn versions:set -DremoveSnapshot
    - mvn -P ossrh -B -s settings.xml verify
    - mvn -P ossrh -B -s settings.xml deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'