stages:
    - deploy

deploy:
  image: crowdar/pipeline:1.0
  stage: deploy
  script:
    - bash create-settings.sh
    - if [ $CI_COMMIT_BRANCH == "master" ] || [ $CI_COMMIT_BRANCH == "main" ]; then mvn versions:set -DremoveSnapshot; fi
    - mvn -B -s settings.xml verify 
    - mvn -B -s settings.xml deploy 

  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"' 
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main"'
