image: crowdar/pipeline:1.0

pipelines:

  branches:
    staging:
      - step:
          name: Build and deploy SNAPSHOT artifact to private Nexus
          trigger: automatic
          caches:
            - maven # Cache any dependencies we download, speeds up build times.
          script:
            - bash create-settings.sh # Create our settings.xml file.  Will fail if environment variables aren't set properly.
            - mvn -B -s settings.xml verify 
            - mvn -B -s settings.xml deploy 
  
    master:
      - step:
          name: Build and deploy release artifact to private Nexus
          trigger: automatic
          caches:
            - maven # Cache any dependencies we download, speeds up build times.
          script:
            - bash create-settings.sh # Create our settings.xml file.  Will fail if environment variables aren't set properly.
            - mvn versions:set -DremoveSnapshot
            - mvn -B -s settings.xml verify 
            - mvn -B -s settings.xml deploy 
      