image: maven:3.3.9-jdk-8

pipelines:
  branches:
    staging:  
      - step:
          name: Build and Deploy Release Artifact
          trigger: automatic
          caches:
            - maven # Cache any dependencies we download, speeds up build times.
          script:
            - bash create-settings.sh # Create our settings.xml file.  Will fail if environment variables aren't set properly.
            - mvn -B -s settings.xml verify # Ensure all artifacts build successfully before we attempt deploy in order to prevent partial deploys.
            - mvn -B -s settings.xml deploy # Now that all builds have completed, we can deploy all the artifacts.
